### ISSUE TITLE
attributes are currently being ignored during parse

### ISSUE THREAD

**Issue by AttilaGal** [fertapric/xmap#3]
When parsing xml where some elements have attributes, the attributes are being ignored. Code example:
```
iex> xml =
 """
...> <?xml version="1.0" encoding="UTF-8"?>
...> <blog>
...>   <post>
...>     <title date="2018-04-23">Hello Elixir!</title>
...>   </post>
...>   <post>
...>     <title date="2018-04-23">Hello World!</title>
...>   </post>
...> </blog>
...> """
iex> XMap.from_xml(xml)
%{"blog" => %{"post" => [
  %{"title" => "Hello Elixir!"},
  %{"title" => "Hello World!"}
]}}
```
it would be nice if the resulting map has the attributes under a separate key, something like this:
```
%{"blog" => %{"post" => [
  %{ "$" => %{"date" => "2018-04-23"}, "title" => "Hello Elixir!"},
  %{ "$" => %{"date" => "2018-04-23"}, "title" => "Hello World!"}
]}}
```

**Comment by fertapric** [comment]
@AttilaGal As you mentioned, there is "information loss" when converting XML to a [`Map`](https://hexdocs.pm/elixir/Map.html) 😞 . 

I would also like to include that information, but I did not find the way to do it. For example, what would be the resulting map for this XML?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<blog>
  <post author="fertapric">
    <title date="2018-04-23">Hello Elixir!</title>
  </post>
  <post author="AttilaGal">
    <title date="2018-04-23">Hello World!</title>
  </post>
</blog>
```

**Comment by AttilaGal** [comment]
I went ahead and peaked at how xml2js handles this for json. The way they handle it:
- element content (with exception of the root), is always wrapped in an array
- if an element has attributes, it is wrapped in an object with the key "$" containing all attributes and the key "_" containing the body if it's a simple value, or the name of the nested element

The xml you suggested would parse to the following json:
```
{
  "blog": {
    "post": [
      {
        "$": {
          "author": "fertapric"
        },
        "title": [
          {
            "_": "Hello Elixir!",
            "$": {
              "date": "2018-04-23"
            }
          }
        ]
      },
      {
        "$": {
          "author": "AttilaGal"
        },
        "title": [
          {
            "_": "Hello World!",
            "$": {
              "date": "2018-04-23"
            }
          }
        ]
      }
    ]
  }
}
```
or if we'd translate that to an elixir Map it would be:
```
%{
  "blog" => %{
    "post" => [
      %{
        "$" => %{
          "author" => "fertapric"
        },
        "title" => [
          %{
            "_" => "Hello Elixir!",
            "$" => %{
              "date" => "2018-04-23"
            }
          }
        ]
      },
      %{
        "$" => %{
          "author" => "AttilaGal"
        },
        "title" => [
          %{
            "_" => "Hello World!",
            "$" => %{
              "date" => "2018-04-23"
            }
          }
        ]
      }
    ]
  }
}
```

Although this would fit my needs nicely, I understand if this is beyond te scope of XMap. If this is the case I'll probably end up making my own library (forked from, your excellent work).

**Comment by fertapric** [comment]
@AttilaGal thanks for taking the time to investigate alternatives :)

Unfortunately, as you said, I think this is beyond the scope of XMap 😞 Forking the project and adapting it to your needs it's the best option here. Ping me if you need any help :)

**Comment by AttilaGal** [comment]
So it's been a while, but I decided to publish my forked version of xmap, I've called it xmax. Hope you don't mind! https://github.com/AttilaGal/xmax
